@startuml
'https://plantuml.com/use-case-diagram

left to right direction

Agente --> (Evaluar\n Solicitud de Crédito)

(Evaluar\n Solicitud de Crédito) <.. (Solicitar Información adicional al\n cliente):<<extend>>
@enduml